classdef tGLFWConstants < matlab.unittest.TestCase
    properties (TestParameter)
        Constant = allConstants()
        ErrorConstant = {
            GLFW.NO_ERROR, ... 
            GLFW.NOT_INITIALIZED, ...
            GLFW.NO_CURRENT_CONTEXT, ...
            GLFW.INVALID_ENUM, ...
            GLFW.INVALID_VALUE, ...
            GLFW.OUT_OF_MEMORY, ...
            GLFW.API_UNAVAILABLE, ...
            GLFW.VERSION_UNAVAILABLE, ...
            GLFW.PLATFORM_ERROR, ...
            GLFW.FORMAT_UNAVAILABLE, ...
            GLFW.NO_WINDOW_CONTEXT, ...
            GLFW.DONT_CARE}
        ErrorID = {
            "GLFW_NO_ERROR", ...
            "GLFW_NOT_INITIALIZED", ...
            "GLFW_NO_CURRENT_CONTEXT", ...
            "GLFW_INVALID_ENUM", ...
            "GLFW_INVALID_VALUE", ...
            "GLFW_OUT_OF_MEMORY", ...
            "GLFW_API_UNAVAILABLE", ...
            "GLFW_VERSION_UNAVAILABLE", ...
            "GLFW_PLATFORM_ERROR", ...
            "GLFW_FORMAT_UNAVAILABLE", ...
            "GLFW_NO_WINDOW_CONTEXT", ...
            "UNKNOWN"}
    end

    methods (Test)
        function constantProperties(testCase, Constant)
            testCase.verifyMatches(Constant.Name, "^(?!GLFW_).+");
            testCase.verifyEqual(Constant.Constant, true, Constant.Name);
            testCase.verifyEqual(Constant.HasDefault, true, Constant.Name);
            testCase.verifyClass(Constant.DefaultValue, ?double, Constant.Name);
        end
    end

    methods (Test, ParameterCombination = "sequential")
        function errorID(testCase, ErrorConstant, ErrorID)
            id = GLFW.errorID(ErrorConstant);
            testCase.verifyEqual(id, ErrorID);
        end
    end
end

function c = allConstants()
mc = meta.class.fromName("GLFW");
c = num2cell(mc.PropertyList);
end