version: 2.1
orbs:
  matlab: mathworks/matlab@0
  codecov: codecov/codecov@1
jobs:
  test:
    parameters:
      matlab-release:
        type: string
    machine:
      image: 'ubuntu-2004:202104-01'
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install xorg-dev
      - matlab/install:
          release: << parameters.matlab-release >>
      - matlab/run-command:
          command: build ci
      - store_test_results:
          path: results
      - codecov/upload
workflows:
  test-matrix:
    jobs:
      - test:
          matrix:
            parameters:
              matlab-release: ["R2020a", "latest"]