version: 2.1
orbs:
  matlab: mathworks/matlab@0
  codecov: codecov/codecov@3
  win: circleci/windows@2
executors:
  linux:
    machine:
      image: ubuntu-2004:202111-02
  windows:
    executor:
      name: win/default
      shell: bash
jobs:
  test:
    parameters:
      executor:
        type: executor
      matlab-release:
        type: string
    executor: <<parameters.executor>>
    steps:
      - checkout
      - run:
          name: Compile GLFW
          command: |
            os=$(uname)
            if [[ $os == Linux ]]; then
              sudo apt-get update && sudo apt-get install xorg-dev
            elif [[ $os = CYGWIN* || $os = MINGW* || $os = MSYS* ]]; then
              choco install cmake
              export PATH="/c/Program Files/CMake/bin:$PATH"
            fi
            ./getdeps.sh
      - matlab/install:
          release: << parameters.matlab-release >>
      - matlab/run-command:
          command: build ci
      - store_test_results:
          path: results
      - codecov/upload
workflows:
  test-matrix:
    jobs:
      - test:
          matrix:
            parameters:
              executor: [linux]
              matlab-release: ["R2020a", "latest"]
      - test:
          matrix:
            parameters:
              executor: [windows]
              matlab-release: ["R2021a", "latest"]