version: 2.1
orbs:
  matlab: mathworks/matlab@0
  codecov: codecov/codecov@3
executors:
  linux-2004:
    machine:
      image: ubuntu-2004:202111-02
  linux-1604:
    machine:
      image: ubuntu-1604:202104-01
jobs:
  test:
    parameters:
      executor:
        type: executor
      matlab-release:
        type: string
    executor: <<parameters.executor>>
    steps:
      - checkout
      - run:
          name: Compile GLFW
          command: |
            os=$(uname)
            if [[ $os == Linux ]]; then
              sudo apt-get update && sudo apt-get install xorg-dev
            fi
            ./getdeps.sh
          shell: bash
      - matlab/install:
          release: << parameters.matlab-release >>
      - matlab/run-command:
          command: build ci
      - store_test_results:
          path: results
      - codecov/upload
workflows:
  test-matrix:
    jobs:
      - test:
          matrix:
            parameters:
              executor: linux-2004
              matlab-release: latest
      - test:
          matrix:
            parameters:
              executor: linux-1604
              matlab-release: R2020a