version: 2.1
orbs:
  matlab: mathworks/matlab@0
  codecov: codecov/codecov@1
  windows: circleci/windows@2
executors:
  linux: &linux-executor
    machine:
      image: ubuntu-2004:202111-02
  macos:
    macos:
      xcode: 13.2.1
  windows:
    win/default
jobs:
  test:
    parameters:
      executor:
        type: executor
      matlab-release:
        type: string
    executor: <<parameters.executor>>
    steps:
      - checkout
      - run:
          name: Compile GLFW
          command: |
            if [[ $(uname) == Linux ]]; then
              sudo apt-get update && sudo apt-get install xorg-dev
            fi
            ./getdeps.sh
          shell: bash
      - matlab/install:
          release: << parameters.matlab-release >>
      - matlab/run-command:
          command: build ci
      - store_test_results:
          path: results
      - codecov/upload
workflows:
  test-matrix:
    jobs:
      - test-unix:
          matrix:
            parameters:
              executor: [linux, macos]
              matlab-release: ["R2020a", "latest"]
      - test-windows:
          matrix:
            parameters:
              executor: [windows]
              matlab-release: ["R2021a", "latest"]