version: 2.1
orbs:
  matlab: mathworks/matlab@0
jobs:
  build:
    machine:
      image: 'ubuntu-2004:202104-01'
    steps:
      - checkout
      - run:
          name: Compile GLFW
          command: |
            sudo apt-get update && sudo apt-get install xorg-dev
            git clone --depth 1 --branch 3.3.4 https://github.com/glfw/glfw.git
            mkdir -p deps/glfw/glnxa64
            cp -r glfw/include deps/glfw/include
            cd deps/glfw/glnxa64
            cmake -DBUILD_SHARED_LIBS=ON ../../../glfw
            make
      - matlab/install
      - matlab/run-tests:
          source-folder: src
