version: 2.1
orbs:
  matlab: mathworks/matlab@0
jobs:
  build:
    machine:
      image: 'ubuntu-2004:202104-01'
    steps:
      - checkout
      - run:
          name: Compile GLFW
          command: |
            sudo apt-get update && sudo apt-get install xorg-dev
            ./getdeps.sh
      - matlab/install
      - matlab/run-tests:
          source-folder: src
