version: 2.1
orbs:
  matlab: mathworks/matlab@0
  codecov: codecov/codecov@1
jobs:
  test:
    parameters:
      matlab-release:
        type: string
    machine:
      image: 'ubuntu-2004:202104-01'
    steps:
      - checkout
      - run:
          name: Compile GLFW
          command: |
            sudo apt-get update && sudo apt-get install xorg-dev
            ./getdeps.sh
      - matlab/install:
          release: << parameters.matlab-release >>
      - matlab/run-tests:
          source-folder: src
          test-results-junit: test-results/matlab/results.xml
          code-coverage-cobertura: coverage.xml
      - store_test_results:
          path: test-results
      - codecov/upload
workflows:
  test-matrix:
    jobs:
      - test:
          matrix:
            parameters:
              matlab-release: ["R2020a", "latest"]