version: 2.1
orbs:
  matlab: mathworks/matlab@0
jobs:
  build:
    machine:
      image: 'ubuntu-2004:202104-01'
    steps:
      - checkout
      - run:
          name: Install GLFW
          command: |
            sudo apt-get update && sudo apt-get install xorg-dev
            git clone --depth 1 --branch 3.3.4 https://github.com/glfw/glfw.git
            cd glfw
            cmake -DBUILD_SHARED_LIBS=ON .
            make
            sudo make install
            cd ..
      - matlab/install
      - matlab/run-tests
          source-folder: src
