name: Build

on:
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
  
jobs:
  build-glfw:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            computer: glnxa64
          
          - os: macos-latest
            computer: maci64
          
          - os: windows-latest
            computer: win64
    
    steps:
      - name: Checkout GLFW
        uses: actions/checkout@v2
        with:
          repository: glfw/glfw
          ref: 3.3.4
    
      - name: Compile GLFW
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install xorg-dev
          fi
          cmake -DCMAKE_INSTALL_PREFIX=${{ matrix.computer }} -DBUILD_SHARED_LIBS=ON .
          cmake --build . --target install
      
      - name: Store GLFW binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.computer }}
          path: ${{ matrix.computer }}
  
  build-matlab-glfw:
    runs-on: ubuntu-latest
    needs: [build-glfw]
    
    steps:
      - name: Checkout matlab-glfw
        uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: glnxa64
          path: deps/glfw/glnxa64
      
      - uses: actions/download-artifact@v2
        with:
          name: maci64
          path: deps/glfw/maci64
          
      - uses: actions/download-artifact@v2
        with:
          name: win64
          path: deps/glfw/win64
          
      - run: zip -r matlab-glfw.zip .
      
      - uses: actions/upload-artifact@v2
        with:
          name: matlab-glfw
          path: matlab-glfw.zip
          
