name: Build

on:
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
  
jobs:
  build-glfw:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            computer: glnxa64
          
          - os: macos-latest
            computer: maci64
          
          - os: windows-latest
            computer: win64
    
    steps:
      - name: Checkout matlab-glfw
        uses: actions/checkout@v2
    
      - name: Compile GLFW
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install xorg-dev
          fi
          ./getdeps.sh
      
      - name: Store GLFW binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.computer }}
          path: deps/glfw/${{ matrix.computer }}
  
  build-matlab-glfw:
    runs-on: ubuntu-latest
    needs: [build-glfw]
    
    steps:
      - name: Checkout matlab-glfw
        uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: glnxa64
          path: deps/glfw/glnxa64
      
      - uses: actions/download-artifact@v2
        with:
          name: maci64
          path: deps/glfw/maci64
          
      - uses: actions/download-artifact@v2
        with:
          name: win64
          path: deps/glfw/win64
      
      - uses: matlab-actions/setup-matlab@v1

      - name: Package toolbox
        uses: matlab-actions/run-command@v1
        with:
          command: package

      - uses: actions/upload-artifact@v2
        with:
          name: matlab-glfw.mltbx
          path: matlab-glfw.mltbx
          if-no-files-found: error
