name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install GLFW
        run: sudo apt-get install libglfw3-dev libgl1 libgl1-mesa-dev xorg-dev libxcursor-dev libxinerama-dev libwayland-bin
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
      
      - name: Run MATLAB Tests
        uses: matlab-actions/run-tests@v1
