name: Create release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
  
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            computer: glnxa64
          
          - os: macos-latest
            computer: maci64
          
          - os: windows-latest
            computer: win64
    
    steps:
      - name: Checkout matlab-glfw
        uses: actions/checkout@v2
    
      - name: Install system dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install xorg-dev
          fi

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Compile GLFW and MEX binaries
        uses: matlab-actions/run-command@v1
        with:
          command: build("compile")

      - name: Store GLFW and MEX binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.computer }}
          path: |
            deps/glfw/${{ matrix.computer }}
            src/private/*.mex*
  
  release:
    runs-on: ubuntu-latest
    needs: [compile]
    
    steps:
      - name: Checkout matlab-glfw
        uses: actions/checkout@v2
      
      - name: Download GLFW and MEX binaries
        uses: actions/download-artifact@v2

      - name: Move GLFW and MEX binaries into place
        run: |
          rsync -av glnxa64/ . && rm -rf glnxa64
          rsync -av maci64/ . && rm -rf maci64
          rsync -av win64/ . && rm -rf win64
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Package toolbox
        uses: matlab-actions/run-command@v1
        with:
          command: build("package", true)

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GLFW.mltbx
          asset_name: GLFW.mltbx
          asset_content_type: application/zip
