name: Release

on:
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
  
jobs:
  build-glfw:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            computer: glnxa64
          
          - os: macos-latest
            computer: maci64
          
          - os: windows-latest
            computer: win64
    
    steps:
      - name: Compile GLFW
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install xorg-dev
          fi
          git clone --depth 1 --branch 3.3.4 https://github.com/glfw/glfw.git
          cd glfw
          cmake -DCMAKE_INSTALL_PREFIX=${{ matrix.computer }} -DBUILD_SHARED_LIBS=ON .
          cmake --build . --target install
      
      - name: Cache GLFW binaries
        uses: actions/cache@v2
        with:
          path: ${{ matrix.computer }}
          key: ${{ matrix.computer }}
  
  build-matlab-glfw:
    runs-on: ubuntu-latest
    needs: [build-glfw]
    
    steps:
      - name: Checkout matlab-glfw
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: deps/glfw/glnxa64
          key: glnxa64
      
      - uses: actions/cache@v2
        with:
          path: deps/glfw/maci64
          key: maci64
          
      - uses: actions/cache@v2
        with:
          path: deps/glfw/win64
          key: win64
          
      - run: zip matlab-glfw.zip .
      
      - uses: actions/upload-artifact@v2
        with:
          path: matlab-glfw.zip
          
