name: Release

on:
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            computer: glnxa64
          
          - os: macos-latest
            computer: maci64
          
          - os: windows-latest
            computer: win64
    
    steps:
      - name: Compile GLFW
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install xorg-dev
          fi
          git clone --depth 1 --branch 3.3.4 https://github.com/glfw/glfw.git
          cd glfw
          cmake -DCMAKE_INSTALL_PREFIX=${{ matrix.computer }} -DBUILD_SHARED_LIBS=ON .
          cmake --build . --target install
      
      - name: Cache GLFW binaries
        uses: actions/cache@v2
        with:
          path: ${{ matrix.computer }}
          key: ${{ matrix.computer }}
