name: Create release

on:
  push:
    tags:
      - 'v*'
  
defaults:
  run:
    shell: bash
  
jobs:
  build-glfw:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            computer: glnxa64
          
          - os: macos-latest
            computer: maci64
          
          - os: windows-latest
            computer: win64
    
    steps:
      - name: Checkout matlab-glfw
        uses: actions/checkout@v2
    
      - name: Compile GLFW
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install xorg-dev
          fi
          ./getdeps.sh
      
      - name: Store GLFW binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.computer }}
          path: deps/glfw/${{ matrix.computer }}
  
  release-matlab-glfw:
    runs-on: ubuntu-latest
    needs: [build-glfw]
    
    steps:
      - name: Checkout matlab-glfw
        uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: glnxa64
          path: deps/glfw/glnxa64
      
      - uses: actions/download-artifact@v2
        with:
          name: maci64
          path: deps/glfw/maci64
          
      - uses: actions/download-artifact@v2
        with:
          name: win64
          path: deps/glfw/win64
      
      - uses: matlab-actions/setup-matlab@v1

      - name: Package toolbox
        uses: matlab-actions/run-command@v1
        with:
          command: build("package", true)

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GLFW.mltbx
          asset_name: GLFW.mltbx
          asset_content_type: application/zip
